version: "3.7"

services:
  heart-beater:
    build:
      context: .
    command:
      - python
      - main.py
      - -c
      - ./example-config.yml
      - -l
      - debug
    volumes:
      - .:/app

  a:
    image: nginx

  b:
    image: nginx

  ping:
    image: nginx
