- url: http://localhost:18888
  period: 10
  ping_url: http://localhost:18888
  headers:
    - key: Host
      value: hello.foo.bar
- url: http://foo:bar@localhost:8889
  period: 5
  ping_url: http://localhost:8889
