- url: http://localhost:8888
  period: 10
  ping_url: http://localhost:8888
  headers:
    - name: Host
      value: hello.foo.bar
  timeout:
    total: 180
    connect: 30
    sock_connect: 30
    sock_read: 120
- url: http://foo:bar@localhost:8889
  period: 5
  ping_url: http://localhost:8889
