- url: http://a
  period: 10
  ping_url: http://ping
  headers:
    - name: Host
      value: hello.foo.bar
  timeout:
    total: 180
    connect: 30
    sock_connect: 30
    sock_read: 120
- url: http://b
  cron: "* * * * *"
  ping_url: http://ping
